apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deployment
  labels:
    app: ng
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: ng
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 80
